### ISSUE TITLE
Failed:  Error: [1010]: Invalid Transaction

### ISSUE THREAD

**Issue by soc1c** [hicommonwealth/edgeware-cli#22]
Hi, I'm trying to register an identity:

```
~/.opt/edgeware-cli master
❯ yarn install
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.32s.

~/.opt/edgeware-cli master
❯ yarn api --seed Sočik identity register github soc1c
yarn run v1.15.2
$ ts-node src/cli.ts --seed Sočik identity register github soc1c
Defaulting to local node 127.0.0.1:9944
Making tx: identity.register("github,soc1c")
Failed:  Error: bad seed size
    at Function.nacl.sign.keyPair.fromSeed (/home/user/.opt/edgeware-cli/node_modules/tweetnacl/nacl-fast.js:2315:11)
    at naclKeypairFromSeed (/home/user/.opt/edgeware-cli/node_modules/@polkadot/util-crypto/nacl/keypair/fromSeed.js:31:42)
    at Keyring.addFromSeed (/home/user/.opt/edgeware-cli/node_modules/@polkadot/keyring/index.js:188:125)
    at SwitchMapSubscriber.apiObservable.pipe.operators_1.switchMap [as project] (/home/user/.opt/edgeware-cli/src/cli.ts:153:30)
    at SwitchMapSubscriber._next (/home/user/.opt/edgeware-cli/node_modules/rxjs/src/internal/operators/switchMap.ts:106:21)
    at SwitchMapSubscriber.Subscriber.next (/home/user/.opt/edgeware-cli/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at /home/user/.opt/edgeware-cli/node_modules/rxjs/src/internal/util/subscribeToPromise.ts:8:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/.opt/edgeware-cli master
❯ yarn api --seed Socik identity register github soc1c
yarn run v1.15.2
$ ts-node src/cli.ts --seed Socik identity register github soc1c
Defaulting to local node 127.0.0.1:9944
Making tx: identity.register("github,soc1c")
Failed:  Error: [1010]: Invalid Transaction
    at RpcCoder.checkError (/home/user/.opt/edgeware-cli/node_modules/@polkadot/rpc-provider/coder/index.js:55:13)
    at RpcCoder.decodeResponse (/home/user/.opt/edgeware-cli/node_modules/@polkadot/rpc-provider/coder/index.js:23:10)
    at WsProvider.onSocketMessageResult.response [as onSocketMessageResult] (/home/user/.opt/edgeware-cli/node_modules/@polkadot/rpc-provider/ws/Provider.js:107:35)
    at W3CWebSocket.WsProvider.onSocketMessage.message [as onmessage] (/home/user/.opt/edgeware-cli/node_modules/@polkadot/rpc-provider/ws/Provider.js:91:61)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/user/.opt/edgeware-cli/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/user/.opt/edgeware-cli/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/user/.opt/edgeware-cli/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:189:13)
    at WebSocketConnection.EventEmitter.emit (domain.js:441:20)
    at WebSocketConnection.processFrame (/home/user/.opt/edgeware-cli/node_modules/websocket/lib/WebSocketConnection.js:554:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Syncing edgeware with default config:

```
~/.opt/edgeware-node 10m 47s
❯ ./target/release/edgeware --chain edgeware
Network "edgeware"
2019-03-18 10:39:41 Edgeware Node
2019-03-18 10:39:41   version 0.1.5-0ece0a7-x86_64-linux-gnu
2019-03-18 10:39:41   by Commonwealth Labs, 2018-2019
2019-03-18 10:39:41 Chain specification: Edgeware V0.1.5
2019-03-18 10:39:41 Node name: puzzling-example-0896
2019-03-18 10:39:41 Roles: FULL
2019-03-18 10:39:42 Best block: #75913
2019-03-18 10:39:42 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/Qmbz6T8K15ahHjRMothBho87aBz1UkWLeLEjp9WH7EF2H8
2019-03-18 10:39:42 Kademlia random query has yielded empty results
2019-03-18 10:39:42 Listening for new connections on 127.0.0.1:9944.
2019-03-18 10:39:44 Kademlia random query has yielded empty results
2019-03-18 10:39:46 Applying authority set change forced at block #75900
2019-03-18 10:39:47 Syncing, target=#119240 (1 peers), best: #76080 (0xdebd…b683), finalized #50 (0x4fe9…e7bc), ⬇ 11.9kiB/s ⬆ 0.7kiB/s
2019-03-18 10:39:47 Pausing old validator set: Forced change scheduled after inactivity
2019-03-18 10:39:48 Applying authority set change forced at block #76100
2019-03-18 10:39:49 Pausing old validator set: Forced change scheduled after inactivity
2019-03-18 10:39:50 Applying authority set change forced at block #76300
2019-03-18 10:39:51 Pausing old validator set: Forced change scheduled after inactivity
2019-03-18 10:39:52 Applying authority set change forced at block #76500
2019-03-18 10:39:52 Syncing 116.4 bps, target=#119240 (1 peers), best: #76662 (0x15aa…0721), finalized #50 (0x4fe9…e7bc), ⬇ 55.7kiB/s ⬆ 0.3kiB/s
```

Truffle 5, Node 10, Arch Linux:

```
~/.opt/edge-lockdrop 15s
❯ uname -a
Linux ceres 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux

~/.opt/edge-lockdrop
❯ yarn --version
1.15.2

~/.opt/edge-lockdrop
❯ node --version
v10.15.3

~/.opt/edge-lockdrop
❯ truffle version  
Truffle v5.0.8 (core: 5.0.8)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
```

**Comment by soc1c** [comment]
The `freeBalance` command seems to time out.

```
~/.opt/edgeware-cli master
❯ yarn api -r edgeware balances freeBalance 5H7Jk4UDwZ3JkfbcrX2NprfZYaPJknApeqjiswKJPBPt6LRN
yarn run v1.15.2
$ ts-node src/cli.ts -r edgeware balances freeBalance 5H7Jk4UDwZ3JkfbcrX2NprfZYaPJknApeqjiswKJPBPt6LRN
2019-03-18 10:43:35          API-WS: disconnected from ws://18.222.29.148:9944::1006: connection failed
2019-03-18 10:45:45          API-WS: disconnected from ws://18.222.29.148:9944::1006: connection failed
2019-03-18 10:47:55          API-WS: disconnected from ws://18.222.29.148:9944::1006: connection failed
2019-03-18 10:50:05          API-WS: disconnected from ws://18.222.29.148:9944::1006: connection failed
```

**Comment by chrishobcroft** [comment]
I am also getting this error when calling `balances transfer`:

```
chrishobcroft@thinkpad:~/edgeware$ ./node_modules/edgeware-cli/bin/edge balances freeBalance 5DUrhjfSKXzfxZEGzBfVzFRYg5RdivSubHUk4ZmYUsexhiXD
Defaulting to local node 127.0.0.1:9944
Making query: balances.freeBalance("5DUrhjfSKXzfxZEGzBfVzFRYg5RdivSubHUk4ZmYUsexhiXD")
0
chrishobcroft@thinkpad:~/edgeware$ ./node_modules/edgeware-cli/bin/edge balances transfer 5DUrhjfSKXzfxZEGzBfVzFRYg5RdivSubHUk4ZmYUsexhiXD 1 -s 0x5d2f4dcac83b93c07c1e56c47c885eea86f45db726bc998b23208b098e51cf4f
Defaulting to local node 127.0.0.1:9944
5DFKFQSz4UZbhc84LCmAx9M2vNRpGtjtjRErgAAGSskMhn8p
Making tx: balances.transfer("5DUrhjfSKXzfxZEGzBfVzFRYg5RdivSubHUk4ZmYUsexhiXD,1")
1010: Invalid Transaction (3)
Failed:  Error: 1010: Invalid Transaction (3)
    at RpcCoder.checkError (/home/chrishobcroft/edgeware/node_modules/@polkadot/rpc-provider/coder/index.js:62:13)
    at RpcCoder.decodeResponse (/home/chrishobcroft/edgeware/node_modules/@polkadot/rpc-provider/coder/index.js:23:10)
    at WsProvider.onSocketMessageResult.response [as onSocketMessageResult] (/home/chrishobcroft/edgeware/node_modules/@polkadot/rpc-provider/ws/Provider.js:112:35)
    at W3CWebSocket.WsProvider.onSocketMessage.message [as onmessage] (/home/chrishobcroft/edgeware/node_modules/@polkadot/rpc-provider/ws/Provider.js:94:61)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/chrishobcroft/edgeware/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/chrishobcroft/edgeware/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/chrishobcroft/edgeware/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:189:13)
    at WebSocketConnection.processFrame (/home/chrishobcroft/edgeware/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/chrishobcroft/edgeware/node_modules/websocket/lib/WebSocketConnection.js:323:40
chrishobcroft@thinkpad:~/edgeware$ 
```

**Comment by danielimkk** [comment]
Has anyone fixed this issue? I`m getting the same error when trying to bond funds and set keys

**Comment by drewstone** [comment]
edgeware-identity registrations have been removed from the current runtime, please open a new issue if you have this issue on the updated mainnet/testnets.
