### ISSUE TITLE
Setting session key error

### ISSUE THREAD

**Issue by ilhanu** [hicommonwealth/edgeware-cli#31]
Wanting to set the keys to validate, with the following command (an example): 
`./bin/edge -r edgeware -s "some Mnemonic" session setKey 0x700226abc28052432071bc573e4e3b3e991854db3d461be120364719ea3d9fdd,0xf268b65f8c09b76fefde7e8bb4a9abc76e4a8ecf032febd00800562e895da65e,0xb948da27abc4787543cfa47d117baaa22f4850ce448b1d1ee094fa4af18ad1f6`

The output is as following:

```
/root/edgeware-cli/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/root/edgeware-cli/node_modules/rxjs/internal/util/subscribeTo.js:29:15)
    at Object.subscribeToResult (/root/edgeware-cli/node_modules/rxjs/internal/util/subscribeToResult.js:14:26)
    at SwitchMapSubscriber._innerSub (/root/edgeware-cli/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/root/edgeware-cli/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/root/edgeware-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /root/edgeware-cli/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by drewstone** [comment]
Try `setKeys` not `setKey`
